# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/song/Dropbox/geneStructureBasedRealignment

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/song/Dropbox/geneStructureBasedRealignment

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/song/Dropbox/geneStructureBasedRealignment/CMakeFiles /Users/song/Dropbox/geneStructureBasedRealignment/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/song/Dropbox/geneStructureBasedRealignment/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named geneStructureBasedRealignment

# Build rule for target.
geneStructureBasedRealignment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 geneStructureBasedRealignment
.PHONY : geneStructureBasedRealignment

# fast build rule for target.
geneStructureBasedRealignment/fast:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/build
.PHONY : geneStructureBasedRealignment/fast

Cds.o: Cds.cpp.o

.PHONY : Cds.o

# target to build an object file
Cds.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/Cds.cpp.o
.PHONY : Cds.cpp.o

Cds.i: Cds.cpp.i

.PHONY : Cds.i

# target to preprocess a source file
Cds.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/Cds.cpp.i
.PHONY : Cds.cpp.i

Cds.s: Cds.cpp.s

.PHONY : Cds.s

# target to generate assembly for a file
Cds.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/Cds.cpp.s
.PHONY : Cds.cpp.s

InputParser.o: InputParser.cpp.o

.PHONY : InputParser.o

# target to build an object file
InputParser.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/InputParser.cpp.o
.PHONY : InputParser.cpp.o

InputParser.i: InputParser.cpp.i

.PHONY : InputParser.i

# target to preprocess a source file
InputParser.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/InputParser.cpp.i
.PHONY : InputParser.cpp.i

InputParser.s: InputParser.cpp.s

.PHONY : InputParser.s

# target to generate assembly for a file
InputParser.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/InputParser.cpp.s
.PHONY : InputParser.cpp.s

alignNeedlemanForTranscript.o: alignNeedlemanForTranscript.cpp.o

.PHONY : alignNeedlemanForTranscript.o

# target to build an object file
alignNeedlemanForTranscript.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/alignNeedlemanForTranscript.cpp.o
.PHONY : alignNeedlemanForTranscript.cpp.o

alignNeedlemanForTranscript.i: alignNeedlemanForTranscript.cpp.i

.PHONY : alignNeedlemanForTranscript.i

# target to preprocess a source file
alignNeedlemanForTranscript.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/alignNeedlemanForTranscript.cpp.i
.PHONY : alignNeedlemanForTranscript.cpp.i

alignNeedlemanForTranscript.s: alignNeedlemanForTranscript.cpp.s

.PHONY : alignNeedlemanForTranscript.s

# target to generate assembly for a file
alignNeedlemanForTranscript.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/alignNeedlemanForTranscript.cpp.s
.PHONY : alignNeedlemanForTranscript.cpp.s

alignNeedlemanWunsch.o: alignNeedlemanWunsch.cpp.o

.PHONY : alignNeedlemanWunsch.o

# target to build an object file
alignNeedlemanWunsch.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/alignNeedlemanWunsch.cpp.o
.PHONY : alignNeedlemanWunsch.cpp.o

alignNeedlemanWunsch.i: alignNeedlemanWunsch.cpp.i

.PHONY : alignNeedlemanWunsch.i

# target to preprocess a source file
alignNeedlemanWunsch.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/alignNeedlemanWunsch.cpp.i
.PHONY : alignNeedlemanWunsch.cpp.i

alignNeedlemanWunsch.s: alignNeedlemanWunsch.cpp.s

.PHONY : alignNeedlemanWunsch.s

# target to generate assembly for a file
alignNeedlemanWunsch.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/alignNeedlemanWunsch.cpp.s
.PHONY : alignNeedlemanWunsch.cpp.s

controlLayer.o: controlLayer.cpp.o

.PHONY : controlLayer.o

# target to build an object file
controlLayer.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/controlLayer.cpp.o
.PHONY : controlLayer.cpp.o

controlLayer.i: controlLayer.cpp.i

.PHONY : controlLayer.i

# target to preprocess a source file
controlLayer.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/controlLayer.cpp.i
.PHONY : controlLayer.cpp.i

controlLayer.s: controlLayer.cpp.s

.PHONY : controlLayer.s

# target to generate assembly for a file
controlLayer.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/controlLayer.cpp.s
.PHONY : controlLayer.cpp.s

model.o: model.cpp.o

.PHONY : model.o

# target to build an object file
model.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/model.cpp.o
.PHONY : model.cpp.o

model.i: model.cpp.i

.PHONY : model.i

# target to preprocess a source file
model.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/model.cpp.i
.PHONY : model.cpp.i

model.s: model.cpp.s

.PHONY : model.s

# target to generate assembly for a file
model.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/model.cpp.s
.PHONY : model.cpp.s

myMsa.o: myMsa.cpp.o

.PHONY : myMsa.o

# target to build an object file
myMsa.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/myMsa.cpp.o
.PHONY : myMsa.cpp.o

myMsa.i: myMsa.cpp.i

.PHONY : myMsa.i

# target to preprocess a source file
myMsa.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/myMsa.cpp.i
.PHONY : myMsa.cpp.i

myMsa.s: myMsa.cpp.s

.PHONY : myMsa.s

# target to generate assembly for a file
myMsa.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/myMsa.cpp.s
.PHONY : myMsa.cpp.s

myfunctions.o: myfunctions.cpp.o

.PHONY : myfunctions.o

# target to build an object file
myfunctions.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/myfunctions.cpp.o
.PHONY : myfunctions.cpp.o

myfunctions.i: myfunctions.cpp.i

.PHONY : myfunctions.i

# target to preprocess a source file
myfunctions.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/myfunctions.cpp.i
.PHONY : myfunctions.cpp.i

myfunctions.s: myfunctions.cpp.s

.PHONY : myfunctions.s

# target to generate assembly for a file
myfunctions.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/myfunctions.cpp.s
.PHONY : myfunctions.cpp.s

myutil.o: myutil.cpp.o

.PHONY : myutil.o

# target to build an object file
myutil.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/myutil.cpp.o
.PHONY : myutil.cpp.o

myutil.i: myutil.cpp.i

.PHONY : myutil.i

# target to preprocess a source file
myutil.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/myutil.cpp.i
.PHONY : myutil.cpp.i

myutil.s: myutil.cpp.s

.PHONY : myutil.s

# target to generate assembly for a file
myutil.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/myutil.cpp.s
.PHONY : myutil.cpp.s

nucleotideCodeSubstitutionMatrix.o: nucleotideCodeSubstitutionMatrix.cpp.o

.PHONY : nucleotideCodeSubstitutionMatrix.o

# target to build an object file
nucleotideCodeSubstitutionMatrix.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/nucleotideCodeSubstitutionMatrix.cpp.o
.PHONY : nucleotideCodeSubstitutionMatrix.cpp.o

nucleotideCodeSubstitutionMatrix.i: nucleotideCodeSubstitutionMatrix.cpp.i

.PHONY : nucleotideCodeSubstitutionMatrix.i

# target to preprocess a source file
nucleotideCodeSubstitutionMatrix.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/nucleotideCodeSubstitutionMatrix.cpp.i
.PHONY : nucleotideCodeSubstitutionMatrix.cpp.i

nucleotideCodeSubstitutionMatrix.s: nucleotideCodeSubstitutionMatrix.cpp.s

.PHONY : nucleotideCodeSubstitutionMatrix.s

# target to generate assembly for a file
nucleotideCodeSubstitutionMatrix.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/nucleotideCodeSubstitutionMatrix.cpp.s
.PHONY : nucleotideCodeSubstitutionMatrix.cpp.s

parameters.o: parameters.cpp.o

.PHONY : parameters.o

# target to build an object file
parameters.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/parameters.cpp.o
.PHONY : parameters.cpp.o

parameters.i: parameters.cpp.i

.PHONY : parameters.i

# target to preprocess a source file
parameters.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/parameters.cpp.i
.PHONY : parameters.cpp.i

parameters.s: parameters.cpp.s

.PHONY : parameters.s

# target to generate assembly for a file
parameters.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/parameters.cpp.s
.PHONY : parameters.cpp.s

reAnnotationAndMsa.o: reAnnotationAndMsa.cpp.o

.PHONY : reAnnotationAndMsa.o

# target to build an object file
reAnnotationAndMsa.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/reAnnotationAndMsa.cpp.o
.PHONY : reAnnotationAndMsa.cpp.o

reAnnotationAndMsa.i: reAnnotationAndMsa.cpp.i

.PHONY : reAnnotationAndMsa.i

# target to preprocess a source file
reAnnotationAndMsa.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/reAnnotationAndMsa.cpp.i
.PHONY : reAnnotationAndMsa.cpp.i

reAnnotationAndMsa.s: reAnnotationAndMsa.cpp.s

.PHONY : reAnnotationAndMsa.s

# target to generate assembly for a file
reAnnotationAndMsa.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/reAnnotationAndMsa.cpp.s
.PHONY : reAnnotationAndMsa.cpp.s

song.o: song.cpp.o

.PHONY : song.o

# target to build an object file
song.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/song.cpp.o
.PHONY : song.cpp.o

song.i: song.cpp.i

.PHONY : song.i

# target to preprocess a source file
song.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/song.cpp.i
.PHONY : song.cpp.i

song.s: song.cpp.s

.PHONY : song.s

# target to generate assembly for a file
song.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/song.cpp.s
.PHONY : song.cpp.s

testAlignNeedlemanForTranscript.o: testAlignNeedlemanForTranscript.cpp.o

.PHONY : testAlignNeedlemanForTranscript.o

# target to build an object file
testAlignNeedlemanForTranscript.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testAlignNeedlemanForTranscript.cpp.o
.PHONY : testAlignNeedlemanForTranscript.cpp.o

testAlignNeedlemanForTranscript.i: testAlignNeedlemanForTranscript.cpp.i

.PHONY : testAlignNeedlemanForTranscript.i

# target to preprocess a source file
testAlignNeedlemanForTranscript.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testAlignNeedlemanForTranscript.cpp.i
.PHONY : testAlignNeedlemanForTranscript.cpp.i

testAlignNeedlemanForTranscript.s: testAlignNeedlemanForTranscript.cpp.s

.PHONY : testAlignNeedlemanForTranscript.s

# target to generate assembly for a file
testAlignNeedlemanForTranscript.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testAlignNeedlemanForTranscript.cpp.s
.PHONY : testAlignNeedlemanForTranscript.cpp.s

testAlignNeedlemanWunsch.o: testAlignNeedlemanWunsch.cpp.o

.PHONY : testAlignNeedlemanWunsch.o

# target to build an object file
testAlignNeedlemanWunsch.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testAlignNeedlemanWunsch.cpp.o
.PHONY : testAlignNeedlemanWunsch.cpp.o

testAlignNeedlemanWunsch.i: testAlignNeedlemanWunsch.cpp.i

.PHONY : testAlignNeedlemanWunsch.i

# target to preprocess a source file
testAlignNeedlemanWunsch.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testAlignNeedlemanWunsch.cpp.i
.PHONY : testAlignNeedlemanWunsch.cpp.i

testAlignNeedlemanWunsch.s: testAlignNeedlemanWunsch.cpp.s

.PHONY : testAlignNeedlemanWunsch.s

# target to generate assembly for a file
testAlignNeedlemanWunsch.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testAlignNeedlemanWunsch.cpp.s
.PHONY : testAlignNeedlemanWunsch.cpp.s

testFastaReading.o: testFastaReading.cpp.o

.PHONY : testFastaReading.o

# target to build an object file
testFastaReading.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testFastaReading.cpp.o
.PHONY : testFastaReading.cpp.o

testFastaReading.i: testFastaReading.cpp.i

.PHONY : testFastaReading.i

# target to preprocess a source file
testFastaReading.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testFastaReading.cpp.i
.PHONY : testFastaReading.cpp.i

testFastaReading.s: testFastaReading.cpp.s

.PHONY : testFastaReading.s

# target to generate assembly for a file
testFastaReading.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testFastaReading.cpp.s
.PHONY : testFastaReading.cpp.s

testGetGenomeSequence.o: testGetGenomeSequence.cpp.o

.PHONY : testGetGenomeSequence.o

# target to build an object file
testGetGenomeSequence.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testGetGenomeSequence.cpp.o
.PHONY : testGetGenomeSequence.cpp.o

testGetGenomeSequence.i: testGetGenomeSequence.cpp.i

.PHONY : testGetGenomeSequence.i

# target to preprocess a source file
testGetGenomeSequence.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testGetGenomeSequence.cpp.i
.PHONY : testGetGenomeSequence.cpp.i

testGetGenomeSequence.s: testGetGenomeSequence.cpp.s

.PHONY : testGetGenomeSequence.s

# target to generate assembly for a file
testGetGenomeSequence.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testGetGenomeSequence.cpp.s
.PHONY : testGetGenomeSequence.cpp.s

testGffReading.o: testGffReading.cpp.o

.PHONY : testGffReading.o

# target to build an object file
testGffReading.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testGffReading.cpp.o
.PHONY : testGffReading.cpp.o

testGffReading.i: testGffReading.cpp.i

.PHONY : testGffReading.i

# target to preprocess a source file
testGffReading.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testGffReading.cpp.i
.PHONY : testGffReading.cpp.i

testGffReading.s: testGffReading.cpp.s

.PHONY : testGffReading.s

# target to generate assembly for a file
testGffReading.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testGffReading.cpp.s
.PHONY : testGffReading.cpp.s

testMsa.o: testMsa.cpp.o

.PHONY : testMsa.o

# target to build an object file
testMsa.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testMsa.cpp.o
.PHONY : testMsa.cpp.o

testMsa.i: testMsa.cpp.i

.PHONY : testMsa.i

# target to preprocess a source file
testMsa.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testMsa.cpp.i
.PHONY : testMsa.cpp.i

testMsa.s: testMsa.cpp.s

.PHONY : testMsa.s

# target to generate assembly for a file
testMsa.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testMsa.cpp.s
.PHONY : testMsa.cpp.s

testMultipleThreads.o: testMultipleThreads.cpp.o

.PHONY : testMultipleThreads.o

# target to build an object file
testMultipleThreads.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testMultipleThreads.cpp.o
.PHONY : testMultipleThreads.cpp.o

testMultipleThreads.i: testMultipleThreads.cpp.i

.PHONY : testMultipleThreads.i

# target to preprocess a source file
testMultipleThreads.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testMultipleThreads.cpp.i
.PHONY : testMultipleThreads.cpp.i

testMultipleThreads.s: testMultipleThreads.cpp.s

.PHONY : testMultipleThreads.s

# target to generate assembly for a file
testMultipleThreads.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testMultipleThreads.cpp.s
.PHONY : testMultipleThreads.cpp.s

testMyGffReading.o: testMyGffReading.cpp.o

.PHONY : testMyGffReading.o

# target to build an object file
testMyGffReading.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testMyGffReading.cpp.o
.PHONY : testMyGffReading.cpp.o

testMyGffReading.i: testMyGffReading.cpp.i

.PHONY : testMyGffReading.i

# target to preprocess a source file
testMyGffReading.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testMyGffReading.cpp.i
.PHONY : testMyGffReading.cpp.i

testMyGffReading.s: testMyGffReading.cpp.s

.PHONY : testMyGffReading.s

# target to generate assembly for a file
testMyGffReading.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testMyGffReading.cpp.s
.PHONY : testMyGffReading.cpp.s

testNucleotideCodeSubstitutionMatrix.o: testNucleotideCodeSubstitutionMatrix.cpp.o

.PHONY : testNucleotideCodeSubstitutionMatrix.o

# target to build an object file
testNucleotideCodeSubstitutionMatrix.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testNucleotideCodeSubstitutionMatrix.cpp.o
.PHONY : testNucleotideCodeSubstitutionMatrix.cpp.o

testNucleotideCodeSubstitutionMatrix.i: testNucleotideCodeSubstitutionMatrix.cpp.i

.PHONY : testNucleotideCodeSubstitutionMatrix.i

# target to preprocess a source file
testNucleotideCodeSubstitutionMatrix.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testNucleotideCodeSubstitutionMatrix.cpp.i
.PHONY : testNucleotideCodeSubstitutionMatrix.cpp.i

testNucleotideCodeSubstitutionMatrix.s: testNucleotideCodeSubstitutionMatrix.cpp.s

.PHONY : testNucleotideCodeSubstitutionMatrix.s

# target to generate assembly for a file
testNucleotideCodeSubstitutionMatrix.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testNucleotideCodeSubstitutionMatrix.cpp.s
.PHONY : testNucleotideCodeSubstitutionMatrix.cpp.s

testReAnnotationAndMsa.o: testReAnnotationAndMsa.cpp.o

.PHONY : testReAnnotationAndMsa.o

# target to build an object file
testReAnnotationAndMsa.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testReAnnotationAndMsa.cpp.o
.PHONY : testReAnnotationAndMsa.cpp.o

testReAnnotationAndMsa.i: testReAnnotationAndMsa.cpp.i

.PHONY : testReAnnotationAndMsa.i

# target to preprocess a source file
testReAnnotationAndMsa.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testReAnnotationAndMsa.cpp.i
.PHONY : testReAnnotationAndMsa.cpp.i

testReAnnotationAndMsa.s: testReAnnotationAndMsa.cpp.s

.PHONY : testReAnnotationAndMsa.s

# target to generate assembly for a file
testReAnnotationAndMsa.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testReAnnotationAndMsa.cpp.s
.PHONY : testReAnnotationAndMsa.cpp.s

testRunExonerate.o: testRunExonerate.cpp.o

.PHONY : testRunExonerate.o

# target to build an object file
testRunExonerate.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testRunExonerate.cpp.o
.PHONY : testRunExonerate.cpp.o

testRunExonerate.i: testRunExonerate.cpp.i

.PHONY : testRunExonerate.i

# target to preprocess a source file
testRunExonerate.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testRunExonerate.cpp.i
.PHONY : testRunExonerate.cpp.i

testRunExonerate.s: testRunExonerate.cpp.s

.PHONY : testRunExonerate.s

# target to generate assembly for a file
testRunExonerate.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testRunExonerate.cpp.s
.PHONY : testRunExonerate.cpp.s

testSdiReading.o: testSdiReading.cpp.o

.PHONY : testSdiReading.o

# target to build an object file
testSdiReading.cpp.o:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testSdiReading.cpp.o
.PHONY : testSdiReading.cpp.o

testSdiReading.i: testSdiReading.cpp.i

.PHONY : testSdiReading.i

# target to preprocess a source file
testSdiReading.cpp.i:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testSdiReading.cpp.i
.PHONY : testSdiReading.cpp.i

testSdiReading.s: testSdiReading.cpp.s

.PHONY : testSdiReading.s

# target to generate assembly for a file
testSdiReading.cpp.s:
	$(MAKE) -f CMakeFiles/geneStructureBasedRealignment.dir/build.make CMakeFiles/geneStructureBasedRealignment.dir/testSdiReading.cpp.s
.PHONY : testSdiReading.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... geneStructureBasedRealignment"
	@echo "... Cds.o"
	@echo "... Cds.i"
	@echo "... Cds.s"
	@echo "... InputParser.o"
	@echo "... InputParser.i"
	@echo "... InputParser.s"
	@echo "... alignNeedlemanForTranscript.o"
	@echo "... alignNeedlemanForTranscript.i"
	@echo "... alignNeedlemanForTranscript.s"
	@echo "... alignNeedlemanWunsch.o"
	@echo "... alignNeedlemanWunsch.i"
	@echo "... alignNeedlemanWunsch.s"
	@echo "... controlLayer.o"
	@echo "... controlLayer.i"
	@echo "... controlLayer.s"
	@echo "... model.o"
	@echo "... model.i"
	@echo "... model.s"
	@echo "... myMsa.o"
	@echo "... myMsa.i"
	@echo "... myMsa.s"
	@echo "... myfunctions.o"
	@echo "... myfunctions.i"
	@echo "... myfunctions.s"
	@echo "... myutil.o"
	@echo "... myutil.i"
	@echo "... myutil.s"
	@echo "... nucleotideCodeSubstitutionMatrix.o"
	@echo "... nucleotideCodeSubstitutionMatrix.i"
	@echo "... nucleotideCodeSubstitutionMatrix.s"
	@echo "... parameters.o"
	@echo "... parameters.i"
	@echo "... parameters.s"
	@echo "... reAnnotationAndMsa.o"
	@echo "... reAnnotationAndMsa.i"
	@echo "... reAnnotationAndMsa.s"
	@echo "... song.o"
	@echo "... song.i"
	@echo "... song.s"
	@echo "... testAlignNeedlemanForTranscript.o"
	@echo "... testAlignNeedlemanForTranscript.i"
	@echo "... testAlignNeedlemanForTranscript.s"
	@echo "... testAlignNeedlemanWunsch.o"
	@echo "... testAlignNeedlemanWunsch.i"
	@echo "... testAlignNeedlemanWunsch.s"
	@echo "... testFastaReading.o"
	@echo "... testFastaReading.i"
	@echo "... testFastaReading.s"
	@echo "... testGetGenomeSequence.o"
	@echo "... testGetGenomeSequence.i"
	@echo "... testGetGenomeSequence.s"
	@echo "... testGffReading.o"
	@echo "... testGffReading.i"
	@echo "... testGffReading.s"
	@echo "... testMsa.o"
	@echo "... testMsa.i"
	@echo "... testMsa.s"
	@echo "... testMultipleThreads.o"
	@echo "... testMultipleThreads.i"
	@echo "... testMultipleThreads.s"
	@echo "... testMyGffReading.o"
	@echo "... testMyGffReading.i"
	@echo "... testMyGffReading.s"
	@echo "... testNucleotideCodeSubstitutionMatrix.o"
	@echo "... testNucleotideCodeSubstitutionMatrix.i"
	@echo "... testNucleotideCodeSubstitutionMatrix.s"
	@echo "... testReAnnotationAndMsa.o"
	@echo "... testReAnnotationAndMsa.i"
	@echo "... testReAnnotationAndMsa.s"
	@echo "... testRunExonerate.o"
	@echo "... testRunExonerate.i"
	@echo "... testRunExonerate.s"
	@echo "... testSdiReading.o"
	@echo "... testSdiReading.i"
	@echo "... testSdiReading.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

