# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/song/Dropbox/geneStructureBasedRealignment

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/song/Dropbox/geneStructureBasedRealignment

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/song/Dropbox/geneStructureBasedRealignment/CMakeFiles /Users/song/Dropbox/geneStructureBasedRealignment/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/song/Dropbox/geneStructureBasedRealignment/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AnnotationLiftOver

# Build rule for target.
AnnotationLiftOver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AnnotationLiftOver
.PHONY : AnnotationLiftOver

# fast build rule for target.
AnnotationLiftOver/fast:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/build
.PHONY : AnnotationLiftOver/fast

Cds.o: Cds.cpp.o

.PHONY : Cds.o

# target to build an object file
Cds.cpp.o:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/Cds.cpp.o
.PHONY : Cds.cpp.o

Cds.i: Cds.cpp.i

.PHONY : Cds.i

# target to preprocess a source file
Cds.cpp.i:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/Cds.cpp.i
.PHONY : Cds.cpp.i

Cds.s: Cds.cpp.s

.PHONY : Cds.s

# target to generate assembly for a file
Cds.cpp.s:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/Cds.cpp.s
.PHONY : Cds.cpp.s

InputParser.o: InputParser.cpp.o

.PHONY : InputParser.o

# target to build an object file
InputParser.cpp.o:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/InputParser.cpp.o
.PHONY : InputParser.cpp.o

InputParser.i: InputParser.cpp.i

.PHONY : InputParser.i

# target to preprocess a source file
InputParser.cpp.i:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/InputParser.cpp.i
.PHONY : InputParser.cpp.i

InputParser.s: InputParser.cpp.s

.PHONY : InputParser.s

# target to generate assembly for a file
InputParser.cpp.s:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/InputParser.cpp.s
.PHONY : InputParser.cpp.s

alignNeedlemanForTranscript.o: alignNeedlemanForTranscript.cpp.o

.PHONY : alignNeedlemanForTranscript.o

# target to build an object file
alignNeedlemanForTranscript.cpp.o:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/alignNeedlemanForTranscript.cpp.o
.PHONY : alignNeedlemanForTranscript.cpp.o

alignNeedlemanForTranscript.i: alignNeedlemanForTranscript.cpp.i

.PHONY : alignNeedlemanForTranscript.i

# target to preprocess a source file
alignNeedlemanForTranscript.cpp.i:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/alignNeedlemanForTranscript.cpp.i
.PHONY : alignNeedlemanForTranscript.cpp.i

alignNeedlemanForTranscript.s: alignNeedlemanForTranscript.cpp.s

.PHONY : alignNeedlemanForTranscript.s

# target to generate assembly for a file
alignNeedlemanForTranscript.cpp.s:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/alignNeedlemanForTranscript.cpp.s
.PHONY : alignNeedlemanForTranscript.cpp.s

alignNeedlemanWunsch.o: alignNeedlemanWunsch.cpp.o

.PHONY : alignNeedlemanWunsch.o

# target to build an object file
alignNeedlemanWunsch.cpp.o:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/alignNeedlemanWunsch.cpp.o
.PHONY : alignNeedlemanWunsch.cpp.o

alignNeedlemanWunsch.i: alignNeedlemanWunsch.cpp.i

.PHONY : alignNeedlemanWunsch.i

# target to preprocess a source file
alignNeedlemanWunsch.cpp.i:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/alignNeedlemanWunsch.cpp.i
.PHONY : alignNeedlemanWunsch.cpp.i

alignNeedlemanWunsch.s: alignNeedlemanWunsch.cpp.s

.PHONY : alignNeedlemanWunsch.s

# target to generate assembly for a file
alignNeedlemanWunsch.cpp.s:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/alignNeedlemanWunsch.cpp.s
.PHONY : alignNeedlemanWunsch.cpp.s

controlLayer.o: controlLayer.cpp.o

.PHONY : controlLayer.o

# target to build an object file
controlLayer.cpp.o:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/controlLayer.cpp.o
.PHONY : controlLayer.cpp.o

controlLayer.i: controlLayer.cpp.i

.PHONY : controlLayer.i

# target to preprocess a source file
controlLayer.cpp.i:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/controlLayer.cpp.i
.PHONY : controlLayer.cpp.i

controlLayer.s: controlLayer.cpp.s

.PHONY : controlLayer.s

# target to generate assembly for a file
controlLayer.cpp.s:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/controlLayer.cpp.s
.PHONY : controlLayer.cpp.s

model.o: model.cpp.o

.PHONY : model.o

# target to build an object file
model.cpp.o:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/model.cpp.o
.PHONY : model.cpp.o

model.i: model.cpp.i

.PHONY : model.i

# target to preprocess a source file
model.cpp.i:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/model.cpp.i
.PHONY : model.cpp.i

model.s: model.cpp.s

.PHONY : model.s

# target to generate assembly for a file
model.cpp.s:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/model.cpp.s
.PHONY : model.cpp.s

myfunctions.o: myfunctions.cpp.o

.PHONY : myfunctions.o

# target to build an object file
myfunctions.cpp.o:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/myfunctions.cpp.o
.PHONY : myfunctions.cpp.o

myfunctions.i: myfunctions.cpp.i

.PHONY : myfunctions.i

# target to preprocess a source file
myfunctions.cpp.i:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/myfunctions.cpp.i
.PHONY : myfunctions.cpp.i

myfunctions.s: myfunctions.cpp.s

.PHONY : myfunctions.s

# target to generate assembly for a file
myfunctions.cpp.s:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/myfunctions.cpp.s
.PHONY : myfunctions.cpp.s

myutil.o: myutil.cpp.o

.PHONY : myutil.o

# target to build an object file
myutil.cpp.o:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/myutil.cpp.o
.PHONY : myutil.cpp.o

myutil.i: myutil.cpp.i

.PHONY : myutil.i

# target to preprocess a source file
myutil.cpp.i:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/myutil.cpp.i
.PHONY : myutil.cpp.i

myutil.s: myutil.cpp.s

.PHONY : myutil.s

# target to generate assembly for a file
myutil.cpp.s:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/myutil.cpp.s
.PHONY : myutil.cpp.s

nucleotideCodeSubstitutionMatrix.o: nucleotideCodeSubstitutionMatrix.cpp.o

.PHONY : nucleotideCodeSubstitutionMatrix.o

# target to build an object file
nucleotideCodeSubstitutionMatrix.cpp.o:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/nucleotideCodeSubstitutionMatrix.cpp.o
.PHONY : nucleotideCodeSubstitutionMatrix.cpp.o

nucleotideCodeSubstitutionMatrix.i: nucleotideCodeSubstitutionMatrix.cpp.i

.PHONY : nucleotideCodeSubstitutionMatrix.i

# target to preprocess a source file
nucleotideCodeSubstitutionMatrix.cpp.i:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/nucleotideCodeSubstitutionMatrix.cpp.i
.PHONY : nucleotideCodeSubstitutionMatrix.cpp.i

nucleotideCodeSubstitutionMatrix.s: nucleotideCodeSubstitutionMatrix.cpp.s

.PHONY : nucleotideCodeSubstitutionMatrix.s

# target to generate assembly for a file
nucleotideCodeSubstitutionMatrix.cpp.s:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/nucleotideCodeSubstitutionMatrix.cpp.s
.PHONY : nucleotideCodeSubstitutionMatrix.cpp.s

parameters.o: parameters.cpp.o

.PHONY : parameters.o

# target to build an object file
parameters.cpp.o:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/parameters.cpp.o
.PHONY : parameters.cpp.o

parameters.i: parameters.cpp.i

.PHONY : parameters.i

# target to preprocess a source file
parameters.cpp.i:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/parameters.cpp.i
.PHONY : parameters.cpp.i

parameters.s: parameters.cpp.s

.PHONY : parameters.s

# target to generate assembly for a file
parameters.cpp.s:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/parameters.cpp.s
.PHONY : parameters.cpp.s

reAnnotationAndMsa.o: reAnnotationAndMsa.cpp.o

.PHONY : reAnnotationAndMsa.o

# target to build an object file
reAnnotationAndMsa.cpp.o:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/reAnnotationAndMsa.cpp.o
.PHONY : reAnnotationAndMsa.cpp.o

reAnnotationAndMsa.i: reAnnotationAndMsa.cpp.i

.PHONY : reAnnotationAndMsa.i

# target to preprocess a source file
reAnnotationAndMsa.cpp.i:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/reAnnotationAndMsa.cpp.i
.PHONY : reAnnotationAndMsa.cpp.i

reAnnotationAndMsa.s: reAnnotationAndMsa.cpp.s

.PHONY : reAnnotationAndMsa.s

# target to generate assembly for a file
reAnnotationAndMsa.cpp.s:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/reAnnotationAndMsa.cpp.s
.PHONY : reAnnotationAndMsa.cpp.s

song.o: song.cpp.o

.PHONY : song.o

# target to build an object file
song.cpp.o:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/song.cpp.o
.PHONY : song.cpp.o

song.i: song.cpp.i

.PHONY : song.i

# target to preprocess a source file
song.cpp.i:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/song.cpp.i
.PHONY : song.cpp.i

song.s: song.cpp.s

.PHONY : song.s

# target to generate assembly for a file
song.cpp.s:
	$(MAKE) -f CMakeFiles/AnnotationLiftOver.dir/build.make CMakeFiles/AnnotationLiftOver.dir/song.cpp.s
.PHONY : song.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... AnnotationLiftOver"
	@echo "... Cds.o"
	@echo "... Cds.i"
	@echo "... Cds.s"
	@echo "... InputParser.o"
	@echo "... InputParser.i"
	@echo "... InputParser.s"
	@echo "... alignNeedlemanForTranscript.o"
	@echo "... alignNeedlemanForTranscript.i"
	@echo "... alignNeedlemanForTranscript.s"
	@echo "... alignNeedlemanWunsch.o"
	@echo "... alignNeedlemanWunsch.i"
	@echo "... alignNeedlemanWunsch.s"
	@echo "... controlLayer.o"
	@echo "... controlLayer.i"
	@echo "... controlLayer.s"
	@echo "... model.o"
	@echo "... model.i"
	@echo "... model.s"
	@echo "... myfunctions.o"
	@echo "... myfunctions.i"
	@echo "... myfunctions.s"
	@echo "... myutil.o"
	@echo "... myutil.i"
	@echo "... myutil.s"
	@echo "... nucleotideCodeSubstitutionMatrix.o"
	@echo "... nucleotideCodeSubstitutionMatrix.i"
	@echo "... nucleotideCodeSubstitutionMatrix.s"
	@echo "... parameters.o"
	@echo "... parameters.i"
	@echo "... parameters.s"
	@echo "... reAnnotationAndMsa.o"
	@echo "... reAnnotationAndMsa.i"
	@echo "... reAnnotationAndMsa.s"
	@echo "... song.o"
	@echo "... song.i"
	@echo "... song.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

